/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002109',
        'tertiary-fixed-dim': '#66df75',
        'primary-fixed-dim': '#52e079',
        'on-tertiary-container': '#00390f',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#00531a',
        'surface-container-low': '#f6f3f2',
        'on-secondary-fixed-variant': '#005224',
        'on-surface-variant': '#3d4a3d',
        'on-tertiary-fixed': '#002106',
        'secondary-fixed': '#92f9a7',
        'surface-dim': '#dcd9d9',
        'surface-tint': '#006e2f',
        'on-primary-fixed-variant': '#005322',
        'on-secondary': '#ffffff',
        'outline-variant': '#bccbb9',
        'on-primary': '#ffffff',
        'inverse-primary': '#52e079',
        'tertiary-container': '#31ae4b',
        'inverse-on-surface': '#f3f0f0',
        'on-secondary-fixed': '#00210a',
        'surface-container-high': '#eae8e7',
        'surface-variant': '#e4e2e1',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#83fc8e',
        'surface-container-highest': '#e4e2e1',
        'tertiary': '#006e25',
        'surface-container': '#f0eded',
        'secondary-fixed-dim': '#76dc8d',
        'on-background': '#1b1c1c',
        'surface-container-lowest': '#ffffff',
        'secondary': '#006d32',
        'on-surface': '#1b1c1c',
        'background': '#fbf9f8',
        'secondary-container': '#92f9a7',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#303030',
        'on-secondary-container': '#007435',
        'outline': '#6d7b6c',
        'surface-bright': '#fbf9f8',
        'surface': '#fbf9f8',
        'primary': '#006e2f',
        'on-primary-container': '#003a15',
        'primary-fixed': '#71fe93',
        'primary-container': '#00b050',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        xs: '4px',
        gutter: '16px',
        md: '16px',
        base: '4px',
        'margin-mobile': '20px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'financial-table': ['Hanken Grotesk', 'sans-serif'],
        'display-financial': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'financial-table': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'display-financial': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}